/**
 * The Pearl Foam — the 3-D Apollonian sphere packing, naturally bounded by its enclosing sphere.
 *
 * Construction (unit ball, scaled to radius R): an outer sphere O and four mutually kissing pearls
 * A–D at the vertices of a regular tetrahedron (radius r = 1/(1+√1.5), centres at 1−r). The packing
 * is the orbit of these five spheres under the group generated by inversions in the five "dual"
 * spheres (each passes through the six kissing points of four of the five spheres):
 *   D0: centre 0, radius (1−r)/√3        (dual of A,B,C,D)
 *   Dk: centre −3·vk, radius 2√2          (dual of O and the three pearls other than k)
 * The dual spheres meet pairwise at π/3, so folding p into the fundamental domain converges.
 *
 * Exact distances: F(x,S) = (|x−c|² − ρ²)/(2ρ) is Möbius-covariant, F(p, g⁻¹S) = F(g(p), S)/|g′(p)|,
 * and tracking w = g(∞) through the folds gives each pearl's exact world radius
 * ρ = r·|q−w|² / (|g′|·(|c−w|² − r²)). The world distance then follows from F and ρ:
 * d = 2F / (1 + √(1 + 2F/ρ)). A base sphere is a real pearl only if w lies outside it; O's exterior
 * is a pearl iff |w| < 1. Because every pearl's world radius is known, the shaping below is exact.
 *
 * GPU cost notes (the DE runs for every march step, normal, AO and shadow probe):
 *  - ANGLE/FXC flattens the per-mirror `if`s, so every pass pays for all five fold bodies. The folds
 *    are therefore written branch-free as q += e·f, dr += dr·f with f = k − 1 (exactly 0 outside).
 *  - w is tracked as a null vector W = λ·(w, (1−|w|²)/2, (1+|w|²)/2) of R^{4,1} (conformal model),
 *    where an inversion is the linear reflection W −= 2⟨W,S⟩S: no division, no clamp, and w = ∞
 *    is exact. Only ratios of ⟨W,·⟩ are used, so the scale λ never matters:
 *      ρ_j = ⟨W,X(q)⟩ / (|g′|·⟨W,T_j⟩)   (T_j = sphere j as a unit spacelike vector, X(q) = q's null vector)
 *    and w lies outside sphere j ⇔ ⟨W,T_j⟩ < 0. (q itself stays in R³: its null vector would carry
 *    a rounding error that the folds amplify quadratically.)
 *  - The candidate pearls share σ_k·q / σ_k·W sums and 1/|g′|, and are evaluated four at a time.
 *
 * The packing is space-filling in measure, so the raw envelope is a skin of pixel-sized pearls.
 * Every pearl is shrunk to ρ·(1−s0) − g1 − gEnv(|p|): kissing points open into flyable gaps, pearls
 * below the threshold vanish, and the envelope (where gEnv ramps up) keeps only large pearls, with
 * windows into the foam. A ball-preserving Möbius transform T_a (animated) swells pearls on one
 * side and froths the other, so the foam slowly breathes without ever leaving the ball.
 *
 * Params (uP[i] = params[4i .. 4i+3]):
 *   uP[0] = (Möbius shift a.xyz (|a| < 0.6), DE safety factor)
 *   uP[1] = (ball radius R, proportional shrink s0, absolute erosion g1, envelope erosion gEnv) [g in units of R]
 *   uP[2] = (envelope start (fraction of R), colour per octave of pearl size, colour offset, cavity per octave)
 *   uP[3] = (glow: smallest glowing size (octaves), glow band width (octaves), glowing fraction 0..1,
 *            extra shrink s1 for large pearls: shrink = s0 + s1·min(ρ/r, 1))
 */
import type { FractalDef } from '../core/types';

const MAX_ITER = 24;

const R_IN = 1 / (1 + Math.sqrt(1.5)); // base pearl radius (unit ball)
const C_IN = 1 - R_IN; // base pearl centre distance
const RHO0_2 = (C_IN * C_IN) / 3; // D0 radius²
const M = 3; // Dk centre distance (opposite pearl k)
const RHO_2 = 8; // Dk radius²
const SQ3 = Math.sqrt(3); // |components| of the Dk centres −√3·σk
const S3 = 1 / SQ3;
// First-ring images (candidates across the mirrors): the gap pearl Dk(Xk) opposite each base pearl,
// and the central pearl D0(O's exterior).
const GAP_NEAR = -M + RHO_2 / (M + C_IN - R_IN);
const GAP_FAR = -M + RHO_2 / (M + C_IN + R_IN);
const C_GAP = 0.5 * (GAP_NEAR + GAP_FAR); // along +vk (negative: opposite side)
const R_GAP = 0.5 * (GAP_NEAR - GAP_FAR);
const R_MID = RHO0_2; // central pearl radius (centre 0)

// Conformal model: sphere (c, r) ↦ (c/r, V = (1 − |c|² + r²)/(2r), U = (1 + |c|² − r²)/(2r)),
// ⟨A,B⟩ = a·b + VaVb − UaUb. Points x ↦ λ·(x, (1−|x|²)/2, (1+|x|²)/2); ∞ ↦ (0, −½, ½).
const RHO0 = Math.sqrt(RHO0_2);
const S0V = (1 + RHO0_2) / (2 * RHO0); // D0 = (0, S0V, S0U)
const S0U = (1 - RHO0_2) / (2 * RHO0);
const SKX = SQ3 / (2 * Math.SQRT2); // Dk = (−SKX·σk, 0, SKU)
const SKU = 1 / (2 * Math.SQRT2);
// Candidate pearls (base B, gap G, central M): power of q = q² − KB·(σk·q) + CB (etc.);
// ⟨W,T⟩ = TBX·(σk·W) + TBV·W_V − TBU·W_U (etc.).
const KB = 2 * C_IN * S3, CB = C_IN * C_IN - R_IN * R_IN;
const TBX = (C_IN / R_IN) * S3, TBV = (1 - CB) / (2 * R_IN), TBU = (1 + CB) / (2 * R_IN);
const KG = 2 * C_GAP * S3, CG = C_GAP * C_GAP - R_GAP * R_GAP;
const TGX = (C_GAP / R_GAP) * S3, TGV = (1 - CG) / (2 * R_GAP), TGU = (1 + CG) / (2 * R_GAP);
const CM = R_MID * R_MID;
const TMV = (1 + CM) / (2 * R_MID), TMU = (1 - CM) / (2 * R_MID);
const IR = 1 / R_IN;

const f = (x: number) => x.toPrecision(9);

const GLSL = /* glsl */ `
#define FRACTAL_MAX_ITER ${MAX_ITER}
#define FRACTAL_HAS_ALBEDO

#define APO_R ${f(R_IN)}
#define APO_IR ${f(IR)}
#define APO_RHO0_2 ${f(RHO0_2)}
#define APO_SQ3 ${f(SQ3)}
#define APO_S0V ${f(S0V)}
#define APO_S0U ${f(S0U)}
#define APO_SKX ${f(SKX)}
#define APO_SKU ${f(SKU)}
#define APO_KB ${f(KB)}
#define APO_CB ${f(CB)}
#define APO_TBX ${f(TBX)}
#define APO_TBV ${f(TBV)}
#define APO_TBU ${f(TBU)}
#define APO_KG ${f(KG)}
#define APO_CG ${f(CG)}
#define APO_TGX ${f(TGX)}
#define APO_TGV ${f(TGV)}
#define APO_TGU ${f(TGU)}
#define APO_IRG ${f(1 / R_GAP)}
#define APO_CM ${f(CM)}
#define APO_TMV ${f(TMV)}
#define APO_TMU ${f(TMU)}
#define APO_IRM ${f(1 / R_MID)}

// Inversion in the dual sphere centred at -sqrt(3)*s (radius^2 8) when q is inside it, branch-free
// (f = k - 1 is exactly 0 outside). w follows as the null vector (Wx, WV, WU): the reflection
// W -= 2<W,S>S with S = (-SKX*s, 0, SKU) leaves WV unchanged.
bool apollonianFold(inout vec3 q, inout float dr, inout vec3 Wx, inout float WU, vec3 s) {
  vec3 e = q + APO_SQ3 * s;
  float e2 = dot(e, e);
  bool inside = e2 < 8.0;
  float fk = inside ? 8.0 / e2 - 1.0 : 0.0;
  q += e * fk;
  dr += dr * fk;
  float g = inside ? dot(s, Wx) * (-2.0 * APO_SKX) - WU * (2.0 * APO_SKU) : 0.0; // 2<W,S>
  Wx += (g * APO_SKX) * s;
  WU -= g * APO_SKU;
  return inside;
}

// Exact world distances to four pearls: F2 = 2F (world power distance over radius), om = <W,T>,
// K = <W,X(q)>/|g'| so that the world radius is rho = K/om; om >= 0 means w is inside the sphere
// (the outside of the ball, not a pearl).
void apollonianPearls(vec4 F2, vec4 om, float K, float iK, vec2 shrink, inout float bestD, inout float bestRho) {
  vec4 rho = K / om;
  vec4 d = F2 / (1.0 + sqrt(max(1.0 + F2 * om * iK, 0.0))) + (shrink.x + shrink.y * min(rho * APO_IR, 1.0)) * rho;
  d = mix(vec4(1e10), d, lessThan(om, vec4(0.0)));
  if (d.x < bestD) { bestD = d.x; bestRho = rho.x; }
  if (d.y < bestD) { bestD = d.y; bestRho = rho.y; }
  if (d.z < bestD) { bestD = d.z; bestRho = rho.z; }
  if (d.w < bestD) { bestD = d.w; bestRho = rho.w; }
}

void apollonianPearl(float F2, float om, float K, float iK, vec2 shrink, inout float bestD, inout float bestRho) {
  float rho = K / om;
  float d = F2 / (1.0 + sqrt(max(1.0 + F2 * om * iK, 0.0))) + (shrink.x + shrink.y * min(rho * APO_IR, 1.0)) * rho;
  if (om < 0.0 && d < bestD) { bestD = d; bestRho = rho; }
}

float fractalDE(vec3 p, out vec4 trap) {
  float R = uP[1].x;
  vec3 x = p / R;
  // ball-preserving Möbius transform T_a (a -> 0); conformal factor (1-|a|²)/D; T_a(inf) = -a/|a|²
  vec3 a = uP[0].xyz;
  float a2 = dot(a, a);
  vec3 dxa = x - a;
  float D = max(1.0 - 2.0 * dot(a, x) + a2 * dot(x, x), 1e-6);
  float lam = (1.0 - a2) / D;
  vec3 q = lam * dxa - (dot(dxa, dxa) / D) * a;
  q.x += 1e-9; // below float precision except at q = 0, where the D0 inversion would divide by zero
  float dr = lam;
  // w = T_a(inf) as a null vector: (-a, (a2-1)/2, (a2+1)/2) ~ (w, (1-|w|²)/2, (1+|w|²)/2)
  vec3 Wx = -a;
  float WV = 0.5 * (a2 - 1.0);
  float WU = 0.5 * (a2 + 1.0);

  for (int i = 0; i < FRACTAL_MAX_ITER; i++) {
    if (i >= uIter) break;
    float q2 = dot(q, q);
    bool moved = q2 < APO_RHO0_2;
    float fk = moved ? APO_RHO0_2 / q2 - 1.0 : 0.0;
    q += q * fk;
    dr += dr * fk;
    float g = moved ? WV * (2.0 * APO_S0V) - WU * (2.0 * APO_S0U) : 0.0; // 2<W,D0>
    WV -= g * APO_S0V;
    WU -= g * APO_S0U;
    moved = apollonianFold(q, dr, Wx, WU, vec3(1.0, 1.0, 1.0)) || moved;
    moved = apollonianFold(q, dr, Wx, WU, vec3(-1.0, -1.0, 1.0)) || moved;
    moved = apollonianFold(q, dr, Wx, WU, vec3(1.0, -1.0, -1.0)) || moved;
    moved = apollonianFold(q, dr, Wx, WU, vec3(-1.0, 1.0, -1.0)) || moved;
    if (!moved) break;
  }

  float q2 = dot(q, q);
  float idr = 1.0 / dr;
  float K = (dot(Wx, q) + 0.5 * (WV * (1.0 - q2) - WU * (1.0 + q2))) * idr;
  float iK = 1.0 / K;
  vec4 sq = vec4(q.x + q.y + q.z, q.z - q.x - q.y, q.x - q.y - q.z, q.y - q.x - q.z);
  vec4 sw = vec4(Wx.x + Wx.y + Wx.z, Wx.z - Wx.x - Wx.y, Wx.x - Wx.y - Wx.z, Wx.y - Wx.x - Wx.z);
  float bestD = 1e10, bestRho = 1.0;
  vec2 shrink = vec2(uP[1].y, uP[3].w);
  apollonianPearls((q2 + APO_CB - APO_KB * sq) * (idr * APO_IR), APO_TBX * sw + (APO_TBV * WV - APO_TBU * WU), K, iK, shrink, bestD, bestRho);
  apollonianPearls((q2 + APO_CG - APO_KG * sq) * (idr * APO_IRG), APO_TGX * sw + (APO_TGV * WV - APO_TGU * WU), K, iK, shrink, bestD, bestRho);
  apollonianPearl((q2 - APO_CM) * (idr * APO_IRM), APO_TMV * WV - APO_TMU * WU, K, iK, shrink, bestD, bestRho);
  apollonianPearl((1.0 - q2) * idr, -WV, K, iK, shrink, bestD, bestRho); // O's exterior (pearl iff |w| < 1)

  float rr = length(x);
  float te = clamp((rr - uP[2].x) / (1.0 - uP[2].x), 0.0, 1.0);
  float d = (bestD + uP[1].z + uP[1].w * te * te) * R * uP[0].w;

  // pearl size in octaves below a base pearl (constant over each pearl)
  float oct = max(log2(APO_R / max(bestRho, 1e-12)), 0.0);
  trap.x = fract(oct * uP[2].y + uP[2].z);
  trap.y = clamp(oct * uP[2].w, 0.0, 1.0);
  trap.z = clamp(rr, 0.0, 1.0);
  float band = smoothstep(uP[3].x, uP[3].x + 0.5, oct) * (1.0 - smoothstep(uP[3].x + uP[3].y, uP[3].x + uP[3].y + 0.5, oct));
  float id = floor(oct * 48.0);
  trap.w = band * step(hash11(id + 0.5), uP[3].z);
  return d;
}

// nacre: a normal-dependent hue shift gives each pearl a thin-film sheen
vec3 fractalAlbedo(vec3 p, vec4 trap, vec3 n, vec3 palA, vec3 palB, vec3 palC, vec3 palD) {
  float film = dot(n, vec3(0.36, 0.8, 0.48));
  vec3 base = cosPalette(trap.x, palA, palB, palC, palD);
  vec3 sheen = cosPalette(trap.x + 0.18 * film + 0.1, palA, palB, palC, palD);
  return mix(base, sheen, 0.45) * (0.9 + 0.1 * film);
}
`;

// ---- JS mirror ------------------------------------------------------------------------------

const fract = (v: number) => v - Math.floor(v);
const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
const smoothstep = (a: number, b: number, v: number) => {
  const t = clamp01((v - a) / (b - a));
  return t * t * (3 - 2 * t);
};
/** Mirror of COMMON_GLSL hash11. */
function hash11(v: number): number {
  v = fract(v * 0.1031);
  v *= v + 33.33;
  v *= v + v;
  return fract(v);
}

// Signs σk of the dual-sphere directions (Dk centre = −√3·σk), in fold order.
const SGN = [1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, -1];

/** Exact world distance to one candidate pearl (see GLSL apollonianPearls); invalid → 1e10. */
function pearlD(F2: number, om: number, rho: number, iK: number, s0: number, s1: number): number {
  if (!(om < 0)) return 1e10;
  return F2 / (1 + Math.sqrt(Math.max(1 + F2 * om * iK, 0))) + (s0 + s1 * Math.min(rho * IR, 1)) * rho;
}

/**
 * Distance (and optionally the trap vector) — exact mirror of the GLSL fractalDE.
 * Exported for tooling; the flight code uses `apollonian.de`. All state lives in locals (fast in V8).
 */
export function apollonianEval(
  px: number, py: number, pz: number, P: Float32Array, iter: number, trap: Float64Array | null,
): number {
  const R = P[4];
  const x = px / R, y = py / R, z = pz / R;
  const ax = P[0], ay = P[1], az = P[2];
  const a2 = ax * ax + ay * ay + az * az;
  const dxx = x - ax, dxy = y - ay, dxz = z - az;
  const D = Math.max(1 - 2 * (ax * x + ay * y + az * z) + a2 * (x * x + y * y + z * z), 1e-6);
  const lam = (1 - a2) / D;
  const t = (dxx * dxx + dxy * dxy + dxz * dxz) / D;
  let qx = lam * dxx - t * ax + 1e-9, qy = lam * dxy - t * ay, qz = lam * dxz - t * az;
  let dr = lam;
  // w = T_a(∞) as a null vector (see header)
  let wx = -ax, wy = -ay, wz = -az, wV = 0.5 * (a2 - 1), wU = 0.5 * (a2 + 1);

  const n = Math.min(iter, MAX_ITER);
  for (let i = 0; i < n; i++) {
    const q2 = qx * qx + qy * qy + qz * qz;
    let moved = q2 < RHO0_2;
    if (moved) {
      const fk = RHO0_2 / q2 - 1;
      qx += qx * fk; qy += qy * fk; qz += qz * fk;
      dr += dr * fk;
      const g = wV * (2 * S0V) - wU * (2 * S0U);
      wV -= g * S0V; wU -= g * S0U;
    }
    for (let k = 0; k < 12; k += 3) {
      const sx = SGN[k], sy = SGN[k + 1], sz = SGN[k + 2];
      const ex = qx + SQ3 * sx, ey = qy + SQ3 * sy, ez = qz + SQ3 * sz;
      const e2 = ex * ex + ey * ey + ez * ez;
      if (e2 < RHO_2) {
        const fk = RHO_2 / e2 - 1;
        qx += ex * fk; qy += ey * fk; qz += ez * fk;
        dr += dr * fk;
        const g = (sx * wx + sy * wy + sz * wz) * (-2 * SKX) - wU * (2 * SKU);
        const gx = g * SKX;
        wx += gx * sx; wy += gx * sy; wz += gx * sz;
        wU -= g * SKU;
        moved = true;
      }
    }
    if (!moved) break;
  }

  const q2 = qx * qx + qy * qy + qz * qz;
  const idr = 1 / dr;
  const K = (wx * qx + wy * qy + wz * qz + 0.5 * (wV * (1 - q2) - wU * (1 + q2))) * idr;
  const iK = 1 / K;
  const sq0 = qx + qy + qz, sq1 = qz - qx - qy, sq2 = qx - qy - qz, sq3 = qy - qx - qz;
  const sw0 = wx + wy + wz, sw1 = wz - wx - wy, sw2 = wx - wy - wz, sw3 = wy - wx - wz;
  const s0 = P[5], s1 = P[15];
  let bestD = 1e10, bestRho = 1;
  let F2 = 0, om = 0, rho = 0, dd = 0;
  const hb = idr * IR, ob = TBV * wV - TBU * wU, qb = q2 + CB;
  const hg = idr * (1 / R_GAP), og = TGV * wV - TGU * wU, qg = q2 + CG;
  for (let j = 0; j < 10; j++) {
    switch (j) {
      case 0: F2 = (qb - KB * sq0) * hb; om = TBX * sw0 + ob; break;
      case 1: F2 = (qb - KB * sq1) * hb; om = TBX * sw1 + ob; break;
      case 2: F2 = (qb - KB * sq2) * hb; om = TBX * sw2 + ob; break;
      case 3: F2 = (qb - KB * sq3) * hb; om = TBX * sw3 + ob; break;
      case 4: F2 = (qg - KG * sq0) * hg; om = TGX * sw0 + og; break;
      case 5: F2 = (qg - KG * sq1) * hg; om = TGX * sw1 + og; break;
      case 6: F2 = (qg - KG * sq2) * hg; om = TGX * sw2 + og; break;
      case 7: F2 = (qg - KG * sq3) * hg; om = TGX * sw3 + og; break;
      case 8: F2 = (q2 - CM) * (idr * (1 / R_MID)); om = TMV * wV - TMU * wU; break;
      default: F2 = (1 - q2) * idr; om = -wV; // O's exterior (pearl iff |w| < 1)
    }
    rho = K / om;
    dd = pearlD(F2, om, rho, iK, s0, s1);
    if (dd < bestD) { bestD = dd; bestRho = rho; }
  }

  const rr = Math.hypot(x, y, z);
  const te = clamp01((rr - P[8]) / (1 - P[8]));
  const d = (bestD + P[6] + P[7] * te * te) * R * P[3];

  if (trap) {
    const oct = Math.max(Math.log2(R_IN / Math.max(bestRho, 1e-12)), 0);
    trap[0] = fract(oct * P[9] + P[10]);
    trap[1] = clamp01(oct * P[11]);
    trap[2] = clamp01(rr);
    const band = smoothstep(P[12], P[12] + 0.5, oct) * (1 - smoothstep(P[12] + P[13], P[12] + P[13] + 0.5, oct));
    const id = Math.floor(oct * 48);
    trap[3] = band * (hash11(id + 0.5) <= P[14] ? 1 : 0);
  }
  return d;
}

const DEFAULT_PARAMS = [
  0.0, 0.0, 0.0, 0.85, // Möbius shift a.xyz, DE safety factor
  1.5, 0.06, 0.002, 0.05, // R, shrink s0, erosion g1, envelope erosion gEnv
  0.55, 0.12, 0.0, 0.1, // envelope start, colour/octave, colour offset, cavity/octave
  3.0, 2.5, 0.12, 0.2, // glow from octave, band width, glowing fraction, s1
];

export const apollonian: FractalDef = {
  kind: 'apollonian',
  label: 'Apollonian sphere packing',
  glsl: GLSL,
  de: (x, y, z, params, iter) => apollonianEval(x, y, z, params, iter, null),
  defaultParams: DEFAULT_PARAMS,
  animate: (base, t, out) => {
    for (let i = 0; i < 16; i++) out[i] = base[i];
    const w = (Math.PI * 2) / 240;
    out[0] = base[0] + 0.14 * Math.sin(t * w); // 240 s
    out[1] = base[1] + 0.1 * Math.sin(t * w * 0.83 + 1.7); // 289 s
    out[2] = base[2] + 0.12 * Math.sin(t * w * 1.21 + 4.1); // 198 s
  },
  boundRadius: 1.53,
  // Pearls only appear with more folds (never vanish), so the CPU uses the full GPU budget: with
  // fewer, flight missed pearls drawn at quality high/ultra (up to 0.0085 local units ≈ 0.25 ly).
  cpuIter: MAX_ITER,
  gpuIter: 20,
  dimension: 2.4739,
};
