/**
 * Indra's Web — Knighty's pseudo-Kleinian limit set, seen through its own mirror sphere.
 *
 * The group is generated by reflections in the faces of the box [−c, c]³ and inversion in the
 * sphere |z|² = Size. Box reflections generate translations, so the raw limit set is an infinite
 * lattice; but inversion in the sphere is itself a group element, so the ball |z| < √Size already
 * contains an inverted copy of the entire infinite web, converging on the centre. We render only
 * that ball. With c ≈ √Size the box faces are (nearly) tangent to the mirror sphere, so the web
 * pinches into six cusped arms whose tips just kiss the sphere: a lacy, octahedrally symmetric star
 * with lens-shaped windows, bounded by construction rather than by an arbitrary cut.
 *
 * Orientation: the local frame puts a 3-fold (cube-diagonal) axis of the web along +Y, using the
 * same local→canonical map as sierpinski.ts (x′ = (1,−1,0)/√2, y′ = (1,1,1)/√3, z′ = (−1,−1,2)/√6).
 * From above the six arms read as a six-pointed star; from the side three arms rise and three fall.
 * The open cradle between the three upper arms is where the catalog's key star sits ((0, 1.4, 0),
 * DE ≈ 0.4); with the box axes along local XYZ that point lay exactly on the +Y arm, which buried
 * the star in the lace and put every surface in its soft shadow.
 *
 * Iteration (DE factor df): z ← 2·clamp(z, −c, c) − z;  k = max(Size/|z|², 1);  z ← k·z;  df ← k·df.
 * Final shape (Knighty): max(ρ − Rdisc, |ρ·z_z|/|z|), ρ = |z.xy|, united with small "jewels" at the
 * box corners — Indra's jewels, hanging in the web like dew; the smaller ones glow (trap.w).
 * The estimate f(z)/df is not 1-Lipschitz (df varies across the inversion ball): measured secant
 * slopes reach ≈1.9 near the surface, so the safety factor is 0.6 (≈0.8 let rays tunnel through the
 * zero-thickness lace sheets: speckle). The DE only gains structure with more iterations, so the CPU
 * uses the full FRACTAL_MAX_ITER and stays conservative against every GPU iteration budget.
 *
 * Params (uP[i] = params[4i .. 4i+3]):
 *   uP[0] = (box half-size c.xyz, inversion radius² Size)
 *   uP[1] = (scale S (local units per web unit), disc radius Rdisc, jewel radius, DE safety factor)
 *   uP[2] = (colour gain, colour offset, cavity per octave of df, jewel glow from octave)
 *   uP[3] = (jewel glow band width (octaves), unused, unused, unused)
 */
import type { FractalDef } from '../core/types';

const MAX_ITER = 16;

const GLSL = /* glsl */ `
#define FRACTAL_MAX_ITER ${MAX_ITER}

float fractalDE(vec3 p, out vec4 trap) {
  float S = uP[1].x;
  vec3 c = uP[0].xyz;
  float size = uP[0].w;
  // local (3-fold axis = +Y) -> web frame (box axes)
  vec3 z = (p.x * vec3(0.70710678, -0.70710678, 0.0)
          + p.y * vec3(0.57735027)
          + p.z * vec3(-0.40824829, -0.40824829, 0.81649658)) / S;
  float df = 1.0;
  float orb = 1e10;
  for (int i = 0; i < FRACTAL_MAX_ITER; i++) {
    if (i >= uIter) break;
    z = 2.0 * clamp(z, -c, c) - z;
    float r2 = max(dot(z, z), 1e-20);
    orb = min(orb, r2);
    float k = max(size / r2, 1.0);
    z *= k;
    df *= k;
  }
  float rxy = length(z.xy);
  float dk = max(rxy - uP[1].y, abs(rxy * z.z) / max(length(z), 1e-20));
  float dj = length(abs(z) - c) - uP[1].z;
  float d = max(min(dk, dj) / df * S * uP[1].w, length(p) - S * sqrt(size));

  float oct = log2(df);
  trap.x = fract(sqrt(orb) * uP[2].x + uP[2].y);
  trap.y = clamp(oct * uP[2].z, 0.0, 1.0);
  trap.z = dj < dk ? 1.0 : 0.0;
  float band = smoothstep(uP[2].w, uP[2].w + 0.75, oct) * (1.0 - smoothstep(uP[2].w + uP[3].x, uP[2].w + uP[3].x + 0.75, oct));
  trap.w = trap.z * band;
  return d;
}
`;

// ---- JS mirror ------------------------------------------------------------------------------

const INV_SQRT2 = Math.SQRT1_2;
const INV_SQRT3 = 1 / Math.sqrt(3);
const INV_SQRT6 = 1 / Math.sqrt(6);
const clamp01 = (v: number) => (v < 0 ? 0 : v > 1 ? 1 : v);
const fract = (v: number) => v - Math.floor(v);
const smoothstep = (a: number, b: number, v: number) => {
  const t = clamp01((v - a) / (b - a));
  return t * t * (3 - 2 * t);
};

/**
 * Distance (and optionally the trap vector) — exact mirror of the GLSL fractalDE.
 * Exported for tooling; the flight code uses `kleinian.de`.
 */
export function kleinianEval(
  px: number, py: number, pz: number, P: Float32Array, iter: number, trap: Float64Array | null,
): number {
  const S = P[4];
  const cx = P[0], cy = P[1], cz = P[2], size = P[3];
  let x = (px * INV_SQRT2 + py * INV_SQRT3 - pz * INV_SQRT6) / S;
  let y = (-px * INV_SQRT2 + py * INV_SQRT3 - pz * INV_SQRT6) / S;
  let z = (py * INV_SQRT3 + pz * 2 * INV_SQRT6) / S;
  let df = 1;
  let orb = 1e10;
  const n = Math.min(iter, MAX_ITER);
  for (let i = 0; i < n; i++) {
    x = 2 * (x < -cx ? -cx : x > cx ? cx : x) - x;
    y = 2 * (y < -cy ? -cy : y > cy ? cy : y) - y;
    z = 2 * (z < -cz ? -cz : z > cz ? cz : z) - z;
    const r2 = Math.max(x * x + y * y + z * z, 1e-20);
    if (r2 < orb) orb = r2;
    const k = Math.max(size / r2, 1);
    x *= k; y *= k; z *= k;
    df *= k;
  }
  const rxy = Math.sqrt(x * x + y * y);
  const dk = Math.max(rxy - P[5], Math.abs(rxy * z) / Math.max(Math.sqrt(x * x + y * y + z * z), 1e-20));
  const jx = Math.abs(x) - cx, jy = Math.abs(y) - cy, jz = Math.abs(z) - cz;
  const dj = Math.sqrt(jx * jx + jy * jy + jz * jz) - P[6];
  const d = Math.max((Math.min(dk, dj) / df) * S * P[7], Math.sqrt(px * px + py * py + pz * pz) - S * Math.sqrt(size));
  if (trap) {
    const oct = Math.log2(df);
    trap[0] = fract(Math.sqrt(orb) * P[8] + P[9]);
    trap[1] = clamp01(oct * P[10]);
    trap[2] = dj < dk ? 1 : 0;
    const band = smoothstep(P[11], P[11] + 0.75, oct) * (1 - smoothstep(P[11] + P[12], P[11] + P[12] + 0.75, oct));
    trap[3] = trap[2] * band;
  }
  return d;
}

const C0 = 0.985;
const DEFAULT_PARAMS = [
  C0, C0, C0, 1.0, // box half-size c, inversion radius² Size
  1.5, 0.93, 0.09, 0.6, // S, disc radius, jewel radius, DE safety
  0.9, 0.05, 0.06, 2.0, // colour gain, colour offset, cavity/octave, jewel glow from octave
  2.0, 0.0, 0.0, 0.0, // glow band width
];

export const kleinian: FractalDef = {
  kind: 'kleinian',
  label: 'Pseudo-Kleinian limit set (Knighty)',
  glsl: GLSL,
  de: (x, y, z, params, iter) => kleinianEval(x, y, z, params, iter, null),
  defaultParams: DEFAULT_PARAMS,
  animate: (base, t, out) => {
    for (let i = 0; i < 16; i++) out[i] = base[i];
    const w = (Math.PI * 2) / 200;
    out[0] = base[0] - 0.012 * (0.5 + 0.5 * Math.sin(t * w)); // 200 s
    out[1] = base[1] - 0.012 * (0.5 + 0.5 * Math.sin(t * w * 0.77 + 2.1)); // 260 s
    out[2] = base[2] - 0.012 * (0.5 + 0.5 * Math.sin(t * w * 1.3 + 4.4)); // 154 s
    out[5] = base[5] - 0.02 * (0.5 + 0.5 * Math.sin(t * w * 0.7 + 1.0)); // 286 s
  },
  boundRadius: 1.53,
  cpuIter: MAX_ITER, // more iterations only add lace: the full budget keeps the CPU conservative
  gpuIter: 13,
  dimension: 2.6,
};
