/**
 * First Light — the curated arena pool of the free daily puzzle (design/20-first-light.md §3.3,
 * design/60-first-light-build.md §L), in nebula LOCAL units, frozen at `clock` (world.ts
 * frozenParams). DailyGen picks one by date and runs the Generator in it.
 *
 * GENERATED by `npx tsx tools/fl-arenas.ts curate <candidates.json…> --write` from the candidates of
 * `npx tsx tools/fl-arenas.ts all` (see that tool for every metric). Every arena here passed the DE
 * reliability check (≤ 1e-3 of 2000 samples with a contact inside the 0.8·DE ball the tracer trusts,
 * ≤ 2 % steeper than Lipschitz 1.25 — measured on 600 samples at curation; with 2000, box 1 / 3 and
 * apollonian 1–3 read 2.2–2.9 %, a warning in fl-check), has a vantage in free space 1.25–1.45 R from the centre with a clear line of
 * sight to it, and lets the generator build levels. The comment above each entry gives:
 *  - R as a fraction of the fractal's bound B (0.06 B: intimate; 0.18–0.22 B: halls);
 *  - placeable: the share of the ball where a medium mass may sit (DE ≥ 2ρ); the build plan's band is
 *    35–75 %. Sierpiński, KIFS (partly) and the Lichtenberg tree are dusts / thin filaments that never
 *    reach it at any scale: their entries are the densest regions found;
 *  - blocked: the share of random chords of the ball that hit structure; enclosure: the share of
 *    directions from the centre that meet structure within R (a lone wall ≈ 50 %);
 *  - yield: generator successes for 1 / 2 / 3 medium masses (6 / 6 / 2 seeds, ≤ 40 / 40 / 60 attempts)
 *    and the mean time per two-mass level.
 * Look at one with `npx tsx tools/fl-preview.ts --arena <nebula>:<i> <outDir>` (i = index among that
 * nebula's entries; `npx tsx tools/fl-solve.ts arenas` lists them) and try it with
 * `npx tsx tools/fl-solve.ts generate --nebula <nebula> --arena <i> --masses medium,medium --seed 1`.
 */
import type { ArenaDef } from './types';

export interface DailyArena {
  nebula: string;
  /** Animation clock (s) the nebula is frozen at. */
  clock: number;
  arena: ArenaDef;
}

export const DAILY_ARENAS: DailyArena[] = [
  // ---- bulb ----
  // R 0.06 B · placeable 53 % · blocked 73 % · enclosure 52 % · yield 6/6 6/6 2/2, 303 ms · vantage clear 0.20 R
  {
    nebula: 'bulb',
    clock: 0,
    arena: {
      centerLocal: [-0.840741, 0.541145, 0.0405],
      radiusLocal: 0.072,
      vantage: { pos: [-0.936817, 0.530053, 0.050204], lookAt: [-0.840741, 0.541145, 0.0405] },
    },
  },
  // R 0.18 B · placeable 48 % · blocked 65 % · enclosure 55 % · yield 6/6 6/6 2/2, 203 ms · vantage clear 0.45 R
  {
    nebula: 'bulb',
    clock: 0,
    arena: {
      centerLocal: [-0.3719, -0.727617, -0.591001],
      radiusLocal: 0.216,
      vantage: { pos: [-0.167508, -0.928557, -0.537359], lookAt: [-0.3719, -0.727617, -0.591001] },
    },
  },
  // R 0.09 B · placeable 49 % · blocked 54 % · enclosure 63 % · yield 6/6 6/6 0/2, 158 ms · vantage clear 0.22 R
  // (replaces R 0.18 B @ -0.574346, -0.750574, 0.235385: 23 DE contacts in 10 000 samples, over the 1e-3 limit)
  {
    nebula: 'bulb',
    clock: 0,
    arena: {
      centerLocal: [0.936114, -0.156726, 0.35101],
      radiusLocal: 0.108,
      vantage: { pos: [1.061003, -0.107759, 0.335845], lookAt: [0.936114, -0.156726, 0.35101] },
    },
  },
  // R 0.18 B · placeable 58 % · blocked 68 % · enclosure 52 % · yield 6/6 6/6 1/2, 158 ms · vantage clear 0.37 R
  {
    nebula: 'bulb',
    clock: 0,
    arena: {
      centerLocal: [-0.867178, 0.373921, -0.351546],
      radiusLocal: 0.216,
      vantage: { pos: [-0.940265, 0.566213, -0.144876], lookAt: [-0.867178, 0.373921, -0.351546] },
    },
  },
  // R 0.06 B · placeable 48 % · blocked 72 % · enclosure 47 % · yield 6/6 6/6 1/2, 241 ms · vantage clear 0.11 R
  {
    nebula: 'bulb',
    clock: 0,
    arena: {
      centerLocal: [0.607187, 0.135945, -0.425825],
      radiusLocal: 0.072,
      vantage: { pos: [0.662946, 0.05967, -0.44865], lookAt: [0.607187, 0.135945, -0.425825] },
    },
  },

  // ---- menger ----
  // R 0.18 B · placeable 53 % · blocked 75 % · enclosure 80 % · yield 6/6 6/6 2/2, 133 ms · vantage clear 1.01 R
  {
    nebula: 'menger',
    clock: 0,
    arena: {
      centerLocal: [-0.861901, -0.759789, -0.736458],
      radiusLocal: 0.324,
      vantage: { pos: [-1.325843, -0.70337, -0.688638], lookAt: [-0.861901, -0.759789, -0.736458] },
    },
  },
  // R 0.18 B · placeable 54 % · blocked 71 % · enclosure 75 % · yield 6/6 6/6 2/2, 125 ms · vantage clear 0.94 R
  {
    nebula: 'menger',
    clock: 0,
    arena: {
      centerLocal: [0.098582, 0.71061, 0.905298],
      radiusLocal: 0.324,
      vantage: { pos: [0.130914, 0.776374, 1.303613], lookAt: [0.098582, 0.71061, 0.905298] },
    },
  },
  // R 0.09 B · placeable 53 % · blocked 75 % · enclosure 69 % · yield 6/6 6/6 2/2, 126 ms · vantage clear 0.20 R
  {
    nebula: 'menger',
    clock: 0,
    arena: {
      centerLocal: [0.654061, 0.544284, 0.912605],
      radiusLocal: 0.162,
      vantage: { pos: [0.556483, 0.602473, 0.744978], lookAt: [0.654061, 0.544284, 0.912605] },
    },
  },
  // R 0.09 B · placeable 54 % · blocked 75 % · enclosure 58 % · yield 6/6 6/6 2/2, 105 ms · vantage clear 0.49 R
  {
    nebula: 'menger',
    clock: 0,
    arena: {
      centerLocal: [-0.250937, -0.729796, -0.319335],
      radiusLocal: 0.162,
      vantage: { pos: [-0.123548, -0.543471, -0.254274], lookAt: [-0.250937, -0.729796, -0.319335] },
    },
  },
  // R 0.09 B · placeable 43 % · blocked 80 % · enclosure 86 % · yield 6/6 6/6 1/2, 127 ms · vantage clear 0.38 R
  {
    nebula: 'menger',
    clock: 0,
    arena: {
      centerLocal: [-0.504304, 0.197113, -0.639495],
      radiusLocal: 0.162,
      vantage: { pos: [-0.715672, 0.214888, -0.692763], lookAt: [-0.504304, 0.197113, -0.639495] },
    },
  },

  // ---- box ----
  // R 0.18 B · placeable 46 % · blocked 60 % · enclosure 52 % · yield 6/6 6/6 2/2, 112 ms · vantage clear 0.16 R
  {
    nebula: 'box',
    clock: 0,
    arena: {
      centerLocal: [-0.536284, -0.702891, 0.16472],
      radiusLocal: 0.288,
      vantage: { pos: [-0.541991, -0.532706, 0.546025], lookAt: [-0.536284, -0.702891, 0.16472] },
    },
  },
  // R 0.13 B · placeable 61 % · blocked 47 % · enclosure 30 % · yield 6/6 6/6 2/2, 130 ms · vantage clear 0.25 R
  {
    nebula: 'box',
    clock: 0,
    arena: {
      centerLocal: [-0.766376, 0.163407, 0.593505],
      radiusLocal: 0.208,
      vantage: { pos: [-0.999532, 0.009266, 0.620478], lookAt: [-0.766376, 0.163407, 0.593505] },
    },
  },
  // R 0.13 B · placeable 56 % · blocked 69 % · enclosure 73 % · yield 6/6 6/6 1/2, 124 ms · vantage clear 0.51 R
  {
    nebula: 'box',
    clock: 0,
    arena: {
      centerLocal: [0.820497, 0.407508, 0.092096],
      radiusLocal: 0.208,
      vantage: { pos: [1.094667, 0.441299, 0.041718], lookAt: [0.820497, 0.407508, 0.092096] },
    },
  },
  // R 0.13 B · placeable 49 % · blocked 56 % · enclosure 63 % · yield 6/6 6/6 1/2, 177 ms · vantage clear 0.15 R
  {
    nebula: 'box',
    clock: 0,
    arena: {
      centerLocal: [-0.429608, 0.740497, -0.055378],
      radiusLocal: 0.208,
      vantage: { pos: [-0.543237, 0.75846, 0.22342], lookAt: [-0.429608, 0.740497, -0.055378] },
    },
  },

  // ---- julia ----
  // R 0.18 B · placeable 45 % · blocked 72 % · enclosure 50 % · yield 6/6 6/6 2/2, 161 ms · vantage clear 0.08 R
  {
    nebula: 'julia',
    clock: 0,
    arena: {
      centerLocal: [0.390878, -0.206513, -0.342432],
      radiusLocal: 0.27,
      vantage: { pos: [0.666448, -0.391788, -0.549812], lookAt: [0.390878, -0.206513, -0.342432] },
    },
  },
  // R 0.06 B · placeable 48 % · blocked 73 % · enclosure 48 % · yield 6/6 6/6 2/2, 160 ms · vantage clear 0.16 R
  {
    nebula: 'julia',
    clock: 0,
    arena: {
      centerLocal: [0.334948, -0.605369, -0.071772],
      radiusLocal: 0.09,
      vantage: { pos: [0.393265, -0.625726, -0.165798], lookAt: [0.334948, -0.605369, -0.071772] },
    },
  },
  // R 0.13 B · placeable 54 % · blocked 61 % · enclosure 52 % · yield 6/6 6/6 2/2, 105 ms · vantage clear 0.14 R
  {
    nebula: 'julia',
    clock: 0,
    arena: {
      centerLocal: [-0.201819, -0.037468, -0.2923],
      radiusLocal: 0.195,
      vantage: { pos: [-0.081485, -0.256444, -0.159948], lookAt: [-0.201819, -0.037468, -0.2923] },
    },
  },
  // R 0.13 B · placeable 53 % · blocked 65 % · enclosure 61 % · yield 6/6 6/6 1/2, 134 ms · vantage clear 0.40 R
  {
    nebula: 'julia',
    clock: 0,
    arena: {
      centerLocal: [0.054027, -0.209591, -0.813497],
      radiusLocal: 0.195,
      vantage: { pos: [-0.223258, -0.154288, -0.811886], lookAt: [0.054027, -0.209591, -0.813497] },
    },
  },
  // R 0.13 B · placeable 53 % · blocked 78 % · enclosure 55 % · yield 6/6 6/6 1/2, 147 ms · vantage clear 0.25 R
  {
    nebula: 'julia',
    clock: 0,
    arena: {
      centerLocal: [-0.289981, 0.316381, 0.168845],
      radiusLocal: 0.195,
      vantage: { pos: [-0.471713, 0.319312, -0.02159], lookAt: [-0.289981, 0.316381, 0.168845] },
    },
  },

  // ---- sierpinski ----
  // R 0.09 B · placeable 79 % (sparse) · blocked 41 % · enclosure 39 % · yield 6/6 6/6 2/2, 143 ms · vantage clear 0.35 R
  {
    nebula: 'sierpinski',
    clock: 0,
    arena: {
      centerLocal: [-0.250578, -0.46305, -0.324658],
      radiusLocal: 0.1404,
      vantage: { pos: [-0.348852, -0.381019, -0.444714], lookAt: [-0.250578, -0.46305, -0.324658] },
    },
  },
  // R 0.06 B · placeable 84 % (sparse) · blocked 44 % · enclosure 50 % · yield 6/6 6/6 2/2, 133 ms · vantage clear 1.20 R
  {
    nebula: 'sierpinski',
    clock: 0,
    arena: {
      centerLocal: [0.736463, -0.499048, -0.477182],
      radiusLocal: 0.0936,
      vantage: { pos: [0.612722, -0.492037, -0.421874], lookAt: [0.736463, -0.499048, -0.477182] },
    },
  },
  // R 0.09 B · placeable 80 % (sparse) · blocked 46 % · enclosure 38 % · yield 6/6 6/6 2/2, 126 ms · vantage clear 0.49 R
  {
    nebula: 'sierpinski',
    clock: 0,
    arena: {
      centerLocal: [-0.202349, -0.441727, -0.626955],
      radiusLocal: 0.1404,
      vantage: { pos: [-0.1487, -0.360395, -0.772926], lookAt: [-0.202349, -0.441727, -0.626955] },
    },
  },
  // R 0.13 B · placeable 85 % (sparse) · blocked 29 % · enclosure 47 % · yield 6/6 6/6 2/2, 130 ms · vantage clear 0.84 R
  {
    nebula: 'sierpinski',
    clock: 0,
    arena: {
      centerLocal: [0.411456, 0.027311, -0.459947],
      radiusLocal: 0.2028,
      vantage: { pos: [0.568535, -0.171652, -0.458384], lookAt: [0.411456, 0.027311, -0.459947] },
    },
  },
  // R 0.09 B · placeable 84 % (sparse) · blocked 38 % · enclosure 38 % · yield 6/6 6/6 2/2, 130 ms · vantage clear 0.52 R
  {
    nebula: 'sierpinski',
    clock: 0,
    arena: {
      centerLocal: [0.139271, -0.444917, 0.961858],
      radiusLocal: 0.1404,
      vantage: { pos: [-0.03094, -0.486581, 1.065478], lookAt: [0.139271, -0.444917, 0.961858] },
    },
  },

  // ---- apollonian ----
  // R 0.09 B · placeable 59 % · blocked 54 % · enclosure 44 % · yield 6/6 6/6 2/2, 273 ms · vantage clear 0.46 R
  {
    nebula: 'apollonian',
    clock: 0,
    arena: {
      centerLocal: [-0.234317, -1.216512, -0.615128],
      radiusLocal: 0.1377,
      vantage: { pos: [-0.112679, -1.315356, -0.543987], lookAt: [-0.234317, -1.216512, -0.615128] },
    },
  },
  // R 0.13 B · placeable 56 % · blocked 59 % · enclosure 41 % · yield 6/6 6/6 2/2, 335 ms · vantage clear 0.27 R
  {
    nebula: 'apollonian',
    clock: 0,
    arena: {
      centerLocal: [-0.156155, -0.404659, 0.789261],
      radiusLocal: 0.1989,
      vantage: { pos: [-0.369411, -0.391103, 0.95186], lookAt: [-0.156155, -0.404659, 0.789261] },
    },
  },
  // R 0.06 B · placeable 58 % · blocked 69 % · enclosure 45 % · yield 6/6 6/6 1/2, 283 ms · vantage clear 0.35 R
  {
    nebula: 'apollonian',
    clock: 0,
    arena: {
      centerLocal: [-0.568652, 0.482767, 0.221143],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.5648, 0.435289, 0.32554], lookAt: [-0.568652, 0.482767, 0.221143] },
    },
  },
  // R 0.18 B · placeable 52 % · blocked 82 % · enclosure 58 % · yield 6/6 4/6 1/2, 656 ms · vantage clear 0.17 R
  {
    nebula: 'apollonian',
    clock: 0,
    arena: {
      centerLocal: [-0.639611, 0.0881, -0.731567],
      radiusLocal: 0.2754,
      vantage: { pos: [-0.746552, 0.18278, -0.418346], lookAt: [-0.639611, 0.0881, -0.731567] },
    },
  },

  // ---- kleinian ----
  // R 0.06 B · placeable 71 % · blocked 38 % · enclosure 22 % · yield 6/6 6/6 2/2, 161 ms · vantage clear 0.49 R
  {
    nebula: 'kleinian',
    clock: 0,
    arena: {
      centerLocal: [-0.703473, -0.667384, 0.417386],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.700334, -0.749908, 0.337715], lookAt: [-0.703473, -0.667384, 0.417386] },
    },
  },
  // R 0.22 B · placeable 71 % · blocked 39 % · enclosure 20 % · yield 6/6 6/6 2/2, 221 ms · vantage clear 0.33 R
  {
    nebula: 'kleinian',
    clock: 0,
    arena: {
      centerLocal: [0.280385, -0.268291, -0.190389],
      radiusLocal: 0.3366,
      vantage: { pos: [0.735768, -0.092979, -0.200598], lookAt: [0.280385, -0.268291, -0.190389] },
    },
  },
  // R 0.09 B · placeable 70 % · blocked 31 % · enclosure 16 % · yield 6/6 6/6 2/2, 167 ms · vantage clear 0.38 R
  {
    nebula: 'kleinian',
    clock: 0,
    arena: {
      centerLocal: [-0.458059, 0.560929, -0.352613],
      radiusLocal: 0.1377,
      vantage: { pos: [-0.287942, 0.568591, -0.278058], lookAt: [-0.458059, 0.560929, -0.352613] },
    },
  },
  // R 0.09 B · placeable 72 % · blocked 34 % · enclosure 47 % · yield 6/6 6/6 1/2, 206 ms · vantage clear 0.25 R
  {
    nebula: 'kleinian',
    clock: 0,
    arena: {
      centerLocal: [-0.228407, 0.005882, 0.427112],
      radiusLocal: 0.1377,
      vantage: { pos: [-0.236386, 0.114505, 0.276466], lookAt: [-0.228407, 0.005882, 0.427112] },
    },
  },
  // R 0.13 B · placeable 55 % · blocked 34 % · enclosure 27 % · yield 6/6 6/6 1/2, 225 ms · vantage clear 0.33 R
  {
    nebula: 'kleinian',
    clock: 0,
    arena: {
      centerLocal: [-0.245199, 0.05948, -0.123453],
      radiusLocal: 0.1989,
      vantage: { pos: [-0.416316, 0.144806, -0.339361], lookAt: [-0.245199, 0.05948, -0.123453] },
    },
  },

  // ---- kifs ----
  // R 0.06 B · placeable 79 % (sparse) · blocked 45 % · enclosure 78 % · yield 6/6 6/6 2/2, 203 ms · vantage clear 0.23 R
  {
    nebula: 'kifs',
    clock: 0,
    arena: {
      centerLocal: [0.443405, 0.437279, -0.90956],
      radiusLocal: 0.0918,
      vantage: { pos: [0.438143, 0.457942, -0.787478], lookAt: [0.443405, 0.437279, -0.90956] },
    },
  },
  // R 0.06 B · placeable 72 % · blocked 65 % · enclosure 42 % · yield 6/6 6/6 2/2, 178 ms · vantage clear 0.42 R
  {
    nebula: 'kifs',
    clock: 0,
    arena: {
      centerLocal: [-0.114353, 0.367894, 0.268829],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.247275, 0.362706, 0.273644], lookAt: [-0.114353, 0.367894, 0.268829] },
    },
  },
  // R 0.06 B · placeable 70 % · blocked 57 % · enclosure 44 % · yield 6/6 6/6 2/2, 148 ms · vantage clear 0.73 R
  {
    nebula: 'kifs',
    clock: 0,
    arena: {
      centerLocal: [-0.049043, -0.386113, 0.241856],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.115092, -0.317111, 0.149149], lookAt: [-0.049043, -0.386113, 0.241856] },
    },
  },
  // R 0.06 B · placeable 74 % · blocked 55 % · enclosure 36 % · yield 6/6 6/6 2/2, 131 ms · vantage clear 0.51 R
  {
    nebula: 'kifs',
    clock: 0,
    arena: {
      centerLocal: [-0.269739, -0.459941, 0.056605],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.355422, -0.48931, -0.040936], lookAt: [-0.269739, -0.459941, 0.056605] },
    },
  },
  // R 0.06 B · placeable 63 % · blocked 59 % · enclosure 53 % · yield 6/6 6/6 1/2, 129 ms · vantage clear 0.34 R
  {
    nebula: 'kifs',
    clock: 0,
    arena: {
      centerLocal: [-0.031682, 0.445582, -0.03629],
      radiusLocal: 0.0918,
      vantage: { pos: [-0.110948, 0.471803, -0.13996], lookAt: [-0.031682, 0.445582, -0.03629] },
    },
  },

  // ---- tree ----
  // R 0.06 B · placeable 86 % (sparse) · blocked 27 % · enclosure 25 % · yield 6/6 6/6 2/2, 150 ms · vantage clear 0.25 R
  {
    nebula: 'tree',
    clock: 0,
    arena: {
      centerLocal: [-0.182372, -0.305073, -0.281955],
      radiusLocal: 0.102,
      vantage: { pos: [-0.287783, -0.258245, -0.357168], lookAt: [-0.182372, -0.305073, -0.281955] },
    },
  },
  // R 0.06 B · placeable 94 % (sparse) · blocked 23 % · enclosure 16 % · yield 6/6 6/6 2/2, 117 ms · vantage clear 0.98 R
  {
    nebula: 'tree',
    clock: 0,
    arena: {
      centerLocal: [-0.166181, 0.263727, -0.040627],
      radiusLocal: 0.102,
      vantage: { pos: [-0.040135, 0.275641, -0.025565], lookAt: [-0.166181, 0.263727, -0.040627] },
    },
  },
  // R 0.13 B · placeable 95 % (sparse) · blocked 19 % · enclosure 16 % · yield 6/6 6/6 2/2, 109 ms · vantage clear 1.09 R
  {
    nebula: 'tree',
    clock: 0,
    arena: {
      centerLocal: [-0.030058, -0.662859, -0.108582],
      radiusLocal: 0.221,
      vantage: { pos: [-0.016818, -0.608425, -0.401626], lookAt: [-0.030058, -0.662859, -0.108582] },
    },
  },
  // R 0.06 B · placeable 93 % (sparse) · blocked 10 % · enclosure 14 % · yield 6/6 6/6 2/2, 112 ms · vantage clear 0.64 R
  {
    nebula: 'tree',
    clock: 0,
    arena: {
      centerLocal: [-0.596809, -0.110558, -0.355274],
      radiusLocal: 0.102,
      vantage: { pos: [-0.636841, -0.146984, -0.228656], lookAt: [-0.596809, -0.110558, -0.355274] },
    },
  },
  // R 0.18 B · placeable 96 % (sparse) · blocked 4 % · enclosure 8 % · yield 6/6 6/6 2/2, 123 ms · vantage clear 0.41 R
  {
    nebula: 'tree',
    clock: 0,
    arena: {
      centerLocal: [-0.328551, 0.538594, -0.558266],
      radiusLocal: 0.306,
      vantage: { pos: [-0.566792, 0.61879, -0.88608], lookAt: [-0.328551, 0.538594, -0.558266] },
    },
  },
];

