/**
 * First Light — the free daily puzzle (design/20-first-light.md §3.3, §7.4; design/60-first-light-build.md
 * §L "DailyGen").
 *
 * One puzzle per UTC day, the same for everyone, deterministic from the date alone (no Math.random, no
 * wall time: the Generator and the gates count evaluations). No DOM except loadDaily's optional fetch,
 * and three.js maths only through the Generator's reach code (Reach.ts), so the Node tools share every line.
 *
 * Schedule (d = days since DAILY_EPOCH 2026-10-02 = #1, weekday in UTC):
 *  - Nebula: NEBULA_CYCLE[d mod 9] (dense / open and absorbing / reflecting alternate), so consecutive
 *    days always differ. Sundays swap in a nebula with dense regions (SUNDAY_NEBULAE, rotating, never
 *    Saturday's or Monday's).
 *  - Arena: that nebula's DAILY_ARENAS in turn (its k-th appearance uses arena k mod n). Sundays take
 *    the harder arenas: the densest of the nebula by `arenaDensity` (the share of random chords of
 *    the ball that hit structure, measured once per arena and cached), the two densest alternating.
 *  - Recipe by weekday (DAILY_RECIPES): Mon one medium mass with an "almost" seed (the unlensed beam
 *    passes it within 3–8 r); Tue one mass, two seeds on one bent leg; Wed two medium; Thu two heavy;
 *    Fri a light and a heavy (which goes where?); Sat three heavy (equal sizes: mixed three-mass budgets
 *    fail the minimal gate) with seeds of 4 % R; Sun two medium and three seeds in a harder arena.
 *    Tiers: 1 = Mon–Tue, 2 = Wed–Fri, 3 = Sat, 4 = Sun.
 *  - Clickable: every daily is generated with the Generator's `reach` option — its masses authored where
 *    the click aimed beside the beam lands from the vantage, and the quick reach gate passed (each mass
 *    one-click reachable with ≥ 400 px² at 1280×720, the click aimed at it solving at 60°, 70° and 100°),
 *    the rule tools/fl-reach.ts audits the bundles with.
 *  - Seed: dailySeed(dateId, 'firstlight'); the Generator retries with its own sub-seeds (maxAttempts).
 *    When a recipe fails it is tried in the nebula's next arena(s) with sub-seed hash2(seed, step) (two
 *    for Mon–Tue, three of the densest for Sun, all of them for Wed–Sat), then the easier recipes of
 *    `fallback` follow (Sat: three medium before two masses), and last a plain one-mass level in every
 *    arena of the nebula, then of the pool. A valid date ≥ DAILY_EPOCH never yields null in practice
 *    (one-mass levels succeed in 64/64 arena × seed runs); tools/fl-daily-build.ts proves it for the
 *    bundled window.
 *  - The level: id `daily-<date>` (the gates' seed, so tools/fl-check reproduces the verdict), chapter
 *    "daily", index = the daily number, name "Daily #N", hints and teach line written from the solution
 *    trace (bends, S-turns, sizes, reflections, close passes; seeds are named by path order).
 *
 * Delivery: tools/fl-daily-build.ts writes public/daily/firstlight/YYYY-MM.json ({ [dateId]: LevelDef },
 * one level per line) for DAILY_WINDOW_DAYS days from the epoch, each generated by generateDaily and
 * fully gated. loadDaily fetches `${baseUrl}daily/firstlight/YYYY-MM.json` (relative to the page: with
 * Vite's base './' that works in dev, in dist/ and under any sub-path), sanitises the day's entry and
 * caches the month; on any failure (no fetch, offline, 404, the dev server's HTML fallback, a bad entry)
 * it generates the same level at runtime. The bundle exists so every browser shows the same bits (other
 * engines may differ in the last bit of Math.pow inside the DEs) and so nobody waits for the generator.
 * Runtime generation cost (Node, one core, all 400 bundled days, fl-daily-check --all --jobs 1), p50 / p95 /
 * max: tier 1 0.02 / 0.06 / 0.09 s, tier 2 0.19 / 0.63 / 1.7 s, tier 4 0.20 / 0.93 / 1.1 s, tier 3 (three
 * heavy masses) 2.0 / 9.8 / 16.6 s. generateDaily itself is synchronous, so the browser passes loadDaily
 * dailyClient.generateDailyAsync, which runs this same generateDaily in a module worker (dailyWorker.ts):
 * the page keeps animating and the level is bit-identical. This module stays Worker-free for the tools.
 * Window build (2026-10-02 … 2027-11-05): 32 of 400 days needed a fallback step (18 Wed–Fri, 12 Saturdays,
 * 2 Sundays), each solved by its own recipe in another arena of its nebula: no day dropped a tier or
 * changed its budget (one Saturday has two seeds instead of three, which its recipe allows).
 *
 * Public API:
 *   loadDaily(dateId, baseUrl = '', generate = generateDaily) → Promise<LevelDef | null>
 *                                                                bundle first, else generate(dateId)
 *   generateDaily(dateId) → LevelDef | null                      deterministic, memoised (returns a copy)
 *   dailyInfo(dateId) → DailyInfo                                number + nebula names (no generation)
 *   dailyPlan(dateId) → DailyPlan | null                         weekday, tier, nebula, arena, recipe
 *   generateDailyReport(dateId) → DailyReport                    generation with diagnostics (tools)
 *   DAILY_RECIPES, DAILY_WINDOW_DAYS, NEBULA_CYCLE, SUNDAY_NEBULAE, arenaDensity(i)
 */
import type { Vec3 } from '../../core/types';
import type { Beam, LevelDef, MassSize, TraceResult } from './types';
import { DAILY_ARENAS } from './dailyArenas';
import { generateLevel } from './Generator';
import { LEVEL_LIMITS, placedMass, sanitizeLevel } from './Level';
import { traceLevel } from './BeamTracer';
import { CRITICAL_IMPACT } from './Geodesic';
import { frozenParams, makeTraceWorld, nebulaFractal } from './world';
import type { GateReport } from './Solver';
import { DAILY_EPOCH, daysBetween, dailyNumber, dailySeed } from '../platform/daily';
import { fnv1a, hash2, mulberry32 } from '../platform/prng';
import { NEBULAE } from '../../universe/catalog';

export interface DailyInfo {
  dateId: string;
  number: number;
  nebula: string;
  /** Short display name for labels ("Menger", "Cauliflower"…). */
  nebulaShort: string;
}

/** 1 = Mon–Tue (one mass), 2 = Wed–Fri (two), 3 = Sat (three), 4 = Sun (two masses, harder arena). */
export type DailyTier = 1 | 2 | 3 | 4;

export interface DailyRecipe {
  tier: DailyTier;
  /** Generator budget, one entry per mass, in bend order. */
  masses: readonly MassSize[];
  /** Goal seeds (default: the Generator's, one per leg). */
  seedCount?: number;
  /** The unlensed beam passes the last seed within [lo, hi] × r (the "almost" moment). */
  almost?: readonly [number, number];
  /** Seed radius × R (default: the Generator's, 0.05). */
  seedRadius?: number;
  /** Generator attempts per try. */
  maxAttempts: number;
  /** Arenas of the nebula to try this recipe in (the scheduled one first). */
  arenas: number;
}

/** Days covered by the pre-generated bundles (tools/fl-daily-build.ts default). */
export const DAILY_WINDOW_DAYS = 400;

const MON: DailyRecipe = { tier: 1, masses: ['medium'], almost: [3, 8], maxAttempts: 80, arenas: 2 };
const TUE: DailyRecipe = { tier: 1, masses: ['medium'], seedCount: 2, almost: [3, 8], maxAttempts: 80, arenas: 2 };
/** Two-mass days try every arena of their nebula before an easier recipe (an arena run succeeds 81–91 % of the time). */
const WED: DailyRecipe = { tier: 2, masses: ['medium', 'medium'], maxAttempts: 80, arenas: Infinity };
const THU: DailyRecipe = { tier: 2, masses: ['heavy', 'heavy'], maxAttempts: 80, arenas: Infinity };
/**
 * The light mass bends first: with the click-aware Generator heavy-then-light succeeded in 35 of 64 arena ×
 * seed runs (its weak second bend left no second seed off the last one's straight leg), light-then-heavy in 52.
 */
const FRI: DailyRecipe = { tier: 2, masses: ['light', 'heavy'], maxAttempts: 80, arenas: Infinity };
/**
 * Seeds of 4 % R (the low end of the design's 4–6 %): three legs leave little free room near structure,
 * and the smaller seed fits it (the old Generator: success within 120 attempts 74/86 arena × seed pairs
 * instead of 58/86). The tolerance and reach gates still guarantee the player-sized window. Three bends
 * in the view plane whose every click keeps 400 px² are rare per attempt: 54 of 64 arena × seed runs
 * succeed within 300 attempts (box arenas far fewer), so a Saturday tries every arena of its nebula.
 */
const SAT: DailyRecipe = { tier: 3, masses: ['heavy', 'heavy', 'heavy'], seedRadius: 0.04, maxAttempts: 300, arenas: Infinity };
/**
 * A Saturday whose nebula has no three-heavy level keeps its three bends with medium masses (smaller
 * shadows fit where heavy ones meet walls: the box arenas give three heavy in ~30 % of runs, three medium
 * in ~70 %) before it drops to two masses.
 */
const SAT_MEDIUM: DailyRecipe = { tier: 3, masses: ['medium', 'medium', 'medium'], seedRadius: 0.04, maxAttempts: 300, arenas: Infinity };
/** In the nebula's densest arenas (the two densest alternate, the third is the spare). */
const SUN: DailyRecipe = { tier: 4, masses: ['medium', 'medium'], seedCount: 3, maxAttempts: 120, arenas: 3 };
/** Last resort: one medium mass, no "almost" window, every arena. */
const PLAIN: DailyRecipe = { tier: 1, masses: ['medium'], maxAttempts: 80, arenas: Infinity };

/** Recipe per UTC weekday (0 = Sunday) and the easier recipes tried when it fails, in order. */
export const DAILY_RECIPES: readonly { recipe: DailyRecipe; fallback: readonly DailyRecipe[] }[] = [
  { recipe: SUN, fallback: [WED, MON] },
  { recipe: MON, fallback: [] },
  { recipe: TUE, fallback: [MON] },
  { recipe: WED, fallback: [MON] },
  { recipe: THU, fallback: [WED, MON] },
  { recipe: FRI, fallback: [WED, MON] },
  { recipe: SAT, fallback: [SAT_MEDIUM, THU, WED, MON] },
];

/**
 * The nebula rotation: dense and open, absorbing and reflecting alternate. The Cauliflower opens (#1).
 * Nebulae of the pool missing here are appended; ids missing from the pool are skipped.
 */
export const NEBULA_CYCLE: readonly string[] = (() => {
  const want = ['bulb', 'kleinian', 'menger', 'tree', 'julia', 'apollonian', 'box', 'sierpinski', 'kifs'];
  const pool: string[] = [];
  for (const a of DAILY_ARENAS) if (!pool.includes(a.nebula)) pool.push(a.nebula);
  return [...want.filter((n) => pool.includes(n)), ...pool.filter((n) => !want.includes(n))];
})();

/** Nebulae with dense regions (curated arenas with ≥ 65 % of chords blocked): the Sunday pool. */
export const SUNDAY_NEBULAE: readonly string[] = (() => {
  const dense = ['menger', 'bulb', 'julia', 'box', 'apollonian', 'kifs'].filter((n) => NEBULA_CYCLE.includes(n));
  return dense.length >= 3 ? dense : NEBULA_CYCLE;
})();

export interface DailyPlan {
  dateId: string;
  /** Days since DAILY_EPOCH (0 = #1). */
  day: number;
  number: number;
  /** UTC weekday, 0 = Sunday. */
  weekday: number;
  tier: DailyTier;
  nebula: string;
  /** Arenas (DAILY_ARENAS indices) in the order they are tried; [0] is the scheduled one. */
  arenas: number[];
  recipe: DailyRecipe;
  fallback: readonly DailyRecipe[];
  seed: number;
}

export interface DailyReport {
  dateId: string;
  plan: DailyPlan | null;
  level: LevelDef | null;
  /** The recipe and arena that produced the level (null when nothing did). */
  recipe: DailyRecipe | null;
  arena: number;
  /** Generator calls before the one that succeeded (0 = the planned recipe in the scheduled arena). */
  step: number;
  /** Generator attempts and trace evaluations over every call. */
  attempts: number;
  evals: number;
  ms: number;
  gates: GateReport | null;
  /** What the hints / teach line were written from. */
  features: DailyFeatures | null;
}

// ---------------------------------------------------------------------------------------------
// Schedule
// ---------------------------------------------------------------------------------------------

const mod = (a: number, n: number): number => ((a % n) + n) % n;

/** UTC weekday of the epoch (Friday). */
const EPOCH_WEEKDAY = new Date(`${DAILY_EPOCH}T00:00:00Z`).getUTCDay();

/** Days since the epoch for a valid id ≥ the epoch, else −1. */
function dayOf(dateId: string): number {
  if (typeof dateId !== 'string') return -1;
  const d = daysBetween(DAILY_EPOCH, dateId);
  return Number.isFinite(d) && d >= 0 ? d : -1;
}

/** DAILY_ARENAS indices of a nebula, in pool order. */
function arenasOf(nebula: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < DAILY_ARENAS.length; i++) if (DAILY_ARENAS[i].nebula === nebula) out.push(i);
  return out;
}

const cycleNebula = (d: number): string => NEBULA_CYCLE[mod(d, NEBULA_CYCLE.length)];

const densityCache = new Map<number, number>();

/**
 * Share of 48 random chords of arena `i`'s ball that hit structure (sphere tracing, contact at 3e-4 R):
 * how obstructed beams are. Deterministic (the stream is seeded by the arena itself), cached; a few ms
 * per arena, computed only for a Sunday's nebula.
 */
export function arenaDensity(i: number): number {
  const hit = densityCache.get(i);
  if (hit !== undefined) return hit;
  const a = DAILY_ARENAS[i];
  if (!a) return 0;
  const fractal = nebulaFractal(a.nebula);
  const params = frozenParams(a.nebula, a.clock);
  const iter = fractal.cpuIter;
  const de = (x: number, y: number, z: number): number => {
    const v = fractal.de(x, y, z, params, iter);
    return v === v ? v : 0;
  };
  const c = a.arena.centerLocal;
  const R = a.arena.radiusLocal;
  const eps = 3e-4 * R;
  const rng = mulberry32(fnv1a(`${a.nebula}:${a.clock}:${c[0]},${c[1]},${c[2]}:${R}:density`));
  const unit = (): Vec3 => {
    const z = 2 * rng() - 1;
    const t = 2 * Math.PI * rng();
    const s = Math.sqrt(Math.max(0, 1 - z * z));
    return [s * Math.cos(t), s * Math.sin(t), z];
  };
  const N = 48;
  let blocked = 0;
  for (let k = 0; k < N; k++) {
    const u = unit();
    const v = unit();
    const ax = c[0] + u[0] * R;
    const ay = c[1] + u[1] * R;
    const az = c[2] + u[2] * R;
    const dx = (v[0] - u[0]) * R;
    const dy = (v[1] - u[1]) * R;
    const dz = (v[2] - u[2]) * R;
    const L = Math.hypot(dx, dy, dz);
    if (!(L > eps)) continue;
    let t = 0;
    for (let s = 0; s < 4000 && t < L; s++) {
      const dd = de(ax + (dx * t) / L, ay + (dy * t) / L, az + (dz * t) / L);
      if (!(dd > eps)) {
        blocked++;
        break;
      }
      t += Math.max(0.8 * dd, eps);
    }
  }
  const out = blocked / N;
  densityCache.set(i, out);
  return out;
}

/** Weekday and nebula of day d ≥ 0 (cheap: no density measurement). */
function scheduleOf(d: number): { weekday: number; nebula: string } {
  const weekday = mod(EPOCH_WEEKDAY + d, 7);
  let nebula = cycleNebula(d);
  if (weekday === 0) {
    // A dense nebula, never Saturday's or Monday's (the cycle's), rotating by Sunday.
    const sunday = Math.floor(d / 7);
    for (let k = 0; k < SUNDAY_NEBULAE.length; k++) {
      const n = SUNDAY_NEBULAE[mod(sunday + k, SUNDAY_NEBULAE.length)];
      if (n !== cycleNebula(d - 1) && n !== cycleNebula(d + 1)) {
        nebula = n;
        break;
      }
    }
  }
  return { weekday, nebula };
}

/** The day's plan, or null for an invalid id or a day before #1. */
export function dailyPlan(dateId: string): DailyPlan | null {
  const d = dayOf(dateId);
  if (d < 0 || NEBULA_CYCLE.length === 0) return null;
  const { weekday, nebula } = scheduleOf(d);
  const { recipe, fallback } = DAILY_RECIPES[weekday];
  let arenas: number[];
  if (weekday === 0) {
    // Densest first (ties: pool order); the two densest alternate between visits.
    const sunday = Math.floor(d / 7);
    const ranked = arenasOf(nebula).sort((x, y) => arenaDensity(y) - arenaDensity(x) || x - y);
    const visit = Math.floor(sunday / SUNDAY_NEBULAE.length);
    if (ranked.length >= 2 && visit % 2 === 1) [ranked[0], ranked[1]] = [ranked[1], ranked[0]];
    arenas = ranked;
  } else {
    const list = arenasOf(nebula);
    const k = mod(Math.floor(d / NEBULA_CYCLE.length), list.length);
    arenas = [...list.slice(k), ...list.slice(0, k)];
  }
  return {
    dateId,
    day: d,
    number: dailyNumber(dateId),
    weekday,
    tier: recipe.tier,
    nebula,
    arenas,
    recipe,
    fallback,
    seed: dailySeed(dateId, 'firstlight'),
  };
}

function shortName(nebula: string): string {
  const name = NEBULAE.find((n) => n.id === nebula)?.name ?? nebula;
  return name
    .replace(/^The\s+/i, '')
    .replace(/\s+(Nebula|Lattice|Foam|Web|Veil|Pyramid|Kaleidoscope)$/i, '')
    .replace(/[’']s$/, '');
}

/** Number and nebula names for labels and share strings (cheap: no generation). */
export function dailyInfo(dateId: string): DailyInfo {
  const d = dayOf(dateId);
  // Not a daily (invalid or before #1): still a stable answer, never a throw.
  const nebula =
    NEBULA_CYCLE.length === 0 ? 'bulb' : d >= 0 ? scheduleOf(d).nebula : NEBULA_CYCLE[mod(dailySeed(String(dateId), 'firstlight'), NEBULA_CYCLE.length)];
  return { dateId, number: dailyNumber(dateId), nebula, nebulaShort: shortName(nebula) };
}

// ---------------------------------------------------------------------------------------------
// Hints and teach line (from the solution trace)
// ---------------------------------------------------------------------------------------------

export interface DailyFeatures {
  masses: number;
  seeds: number;
  sizes: MassSize[];
  /** Reflections before the last goal seed lights. */
  reflections: number;
  /** Consecutive bends turning opposite ways (an S; never across a bounce). */
  sBends: number;
  /** Closest pass of the solved beam to any solution mass (× ρ). */
  closest: number;
  /** Unlensed beam's closest approach to a goal seed (× r). */
  almost: number;
  /** Path position of the first bend as a fraction of the unlensed beam. */
  firstAlong: number;
}

interface Along {
  s: number;
  d: number;
  p: Vec3;
  t: Vec3;
}

/** Closest point of a beam polyline to q: path length, distance, the point and the segment's direction. */
function nearestOn(b: Beam, q: Readonly<Vec3>): Along {
  const P = b.points;
  const n = P.length / 3;
  let best: Along = { s: 0, d: Infinity, p: [P[0], P[1], P[2]], t: [0, 0, 1] };
  for (let i = 0; i + 1 < n; i++) {
    const ax = P[3 * i];
    const ay = P[3 * i + 1];
    const az = P[3 * i + 2];
    const ux = P[3 * i + 3] - ax;
    const uy = P[3 * i + 4] - ay;
    const uz = P[3 * i + 5] - az;
    const uu = ux * ux + uy * uy + uz * uz;
    let f = uu > 0 ? ((q[0] - ax) * ux + (q[1] - ay) * uy + (q[2] - az) * uz) / uu : 0;
    f = f < 0 ? 0 : f > 1 ? 1 : f;
    const p: Vec3 = [ax + f * ux, ay + f * uy, az + f * uz];
    const d = Math.hypot(p[0] - q[0], p[1] - q[1], p[2] - q[2]);
    if (d < best.d) {
      const l = Math.sqrt(uu) || 1;
      best = { s: b.length[i] + f * (b.length[i + 1] - b.length[i]), d, p, t: [ux / l, uy / l, uz / l] };
    }
  }
  return best;
}

const ORDINAL = ['first', 'second', 'third', 'fourth', 'fifth', 'sixth'];
const ordinal = (i: number): string => ORDINAL[i] ?? `#${i + 1}`;

/** "close to the star" / "about a third of the way along the star's beam". */
function alongWords(f: number): string {
  if (!(f >= 0.18)) return 'close to the star';
  const w =
    f < 0.29 ? 'about a quarter of the way' : f < 0.42 ? 'about a third of the way' : f < 0.58 ? 'about halfway' : f < 0.71 ? 'about two-thirds of the way' : f < 0.85 ? 'about three-quarters of the way' : 'near the far end';
  return `${w} along the star's beam`;
}

/**
 * Where a mass sits relative to the beam it bends, in shadow widths (the drawn shadow is the capture
 * disc, radius 2.6 ρ): "a shadow-width from the beam", "with its shadow just clear of the new beam".
 */
function offsetWords(rhoUnits: number, beam: string): string {
  const w = rhoUnits / (2 * CRITICAL_IMPACT);
  if (!(w >= 0.75)) return `with its shadow just clear of the ${beam}`;
  const n = w < 1.25 ? 'a shadow-width' : w < 1.75 ? 'one and a half shadow-widths' : w < 2.5 ? 'two shadow-widths' : 'three shadow-widths';
  return `${n} from the ${beam}`;
}

/**
 * Closest pass (× ρ) that earns the capture remarks: within 1.4 × the critical impact parameter (2.6 ρ)
 * a small misplacement swallows the beam.
 */
const CLOSE_PASS = 3.6;

/** Closest passes (× ρ) within this factor of each other make turns "about as sharp". */
const SHARPER = 1.1;

const SIZE_RANK: Readonly<Record<MassSize, number>> = { light: 0, medium: 1, heavy: 2 };

/**
 * Which size makes the sharper turn in a mixed budget, from the solution trace (`q` = closest pass × that
 * mass's own ρ). The turn depends only on q (α ≈ 2ρ/b), so a light mass hugging the beam out-turns a
 * heavy one passed wide: about half the Friday solutions do exactly that. "" when the trace is unusable.
 */
function sharperWords(bends: readonly { size: MassSize; q: number }[]): string {
  if (bends.length < 2) return '';
  let hi = bends[0].size;
  let lo = hi;
  for (const b of bends) {
    if (SIZE_RANK[b.size] > SIZE_RANK[hi]) hi = b.size;
    if (SIZE_RANK[b.size] < SIZE_RANK[lo]) lo = b.size;
  }
  let qHi = Infinity;
  let qLo = Infinity;
  for (const b of bends) {
    if (b.size === hi) qHi = Math.min(qHi, b.q);
    if (b.size === lo) qLo = Math.min(qLo, b.q);
  }
  if (hi === lo || !(qHi > 0 && qHi < Infinity && qLo > 0 && qLo < Infinity)) return '';
  if (qHi * SHARPER < qLo) return `The ${hi} mass makes the sharper turn.`;
  if (qLo * SHARPER < qHi) return `The ${lo} mass makes the sharper turn: it sits closer to the beam.`;
  return `${bends.length === 2 ? 'Both turns' : 'The turns'} are about as sharp: the ${hi} mass sits farther from the beam.`;
}

const COUNT_WORDS = ['no', 'once', 'twice', 'three times', 'four times', 'five times', 'six times'];

/** Teach lines (≤ 90 chars: the solved card) per what the level shows; describe() picks one. */
const TEACH = {
  corner: ['A bend and a bounce make a corner: pearl walls are mirrors.'],
  bounce: ['Bends and bounces chain: every pearl wall is a mirror.', 'Mirrors and masses both turn light; only the masses are yours to place.'],
  /** Indra's Web reflects too, but its walls are no pearls. */
  cornerWeb: ["A bend and a bounce make a corner: the web's walls are mirrors."],
  bounceWeb: ['Bends and bounces chain: every wall of the web is a mirror.', 'Mirrors and masses both turn light; only the masses are yours to place.'],
  close: [
    'The closer the pass, the harder the bend, until the shadow swallows the light.',
    'Pass near a mass and light bends sharply; pass too near and it never comes back.',
  ],
  mixed: ['A heavy mass bends light harder than a light one at the same distance.', 'The bend grows with the mass: twice the mass, twice the turn at the same distance.'],
  line: ['After a bend light runs straight again: one bend can line up two seeds.', 'Light leaves a bend in a straight line: aim that line and every seed on it lights.'],
  bend: [
    'A mass bends light toward itself: the closer the pass, the stronger the bend.',
    'Halve the distance to a mass and the light bends twice as hard.',
    'Light passing a mass bends toward it, twice as much as Newton predicted.',
  ],
  s: [
    'One mass bends light one way only; an S-shaped path needs two.',
    'A mass only pulls light toward itself: to turn back, the light needs another.',
    'Each mass pulls light toward itself, so turning one way and then back takes two.',
  ],
  series: ['Two bends in series add up.'],
  compose: ['Bends compose: each mass turns the beam once more.', 'Every turn of the light needs a mass of its own: one mass, one bend.'],
} as const;

function describe(level: LevelDef): { hints: [string, string, string]; teach: string; hintMass: number; features: DailyFeatures } {
  const world = makeTraceWorld(level);
  const sol = level.solution.map((m) => placedMass(level, m.size, m.pos));
  const solved: TraceResult = traceLevel(level, world, sol);
  const unlensed: TraceResult = traceLevel(level, world, []);
  const beam = solved.beams[0];
  const goals = level.seeds.filter((s) => s.goal);
  const seedS = goals.map((s) => nearestOn(beam, s.pos).s).sort((a, b) => a - b);
  const lastSeed = seedS.length ? seedS[seedS.length - 1] : Infinity;
  const bends = sol.map((m, i) => ({ i, size: m.size, at: nearestOn(beam, m.pos), rho: m.rho, pos: m.pos })).sort((a, b) => a.at.s - b.at.s);
  // Opposite turns: the side (beam → mass) of bend j made ⟂ to the beam at bend j+1, against its side.
  const side = (b: (typeof bends)[number]): Vec3 => {
    const v: Vec3 = [b.pos[0] - b.at.p[0], b.pos[1] - b.at.p[1], b.pos[2] - b.at.p[2]];
    const l = Math.hypot(v[0], v[1], v[2]) || 1;
    return [v[0] / l, v[1] / l, v[2] / l];
  };
  let reflections = 0;
  const rp = beam.reflections;
  const reflS: number[] = [];
  for (let i = 0; i < rp.length; i += 3) reflS.push(nearestOn(beam, [rp[i], rp[i + 1], rp[i + 2]]).s);
  for (const s of reflS) if (s < lastSeed) reflections++;
  // A bounce between two bends mirrors the beam, so comparing their sides across it says nothing about how
  // the turns look (2026-11-21, 2027-01-23, 2027-07-31 read "back" where the vantage sees the same sense
  // again): such a bend is neither "back" nor "again" and no S.
  const bounced = bends.map((b, j) => j > 0 && reflS.some((s) => s > bends[j - 1].at.s && s < b.at.s));
  const opposite: boolean[] = bends.map(() => false);
  for (let j = 1; j < bends.length; j++) {
    if (bounced[j]) continue;
    const a = side(bends[j - 1]);
    const t = bends[j].at.t;
    const k = a[0] * t[0] + a[1] * t[1] + a[2] * t[2];
    const ap: Vec3 = [a[0] - k * t[0], a[1] - k * t[1], a[2] - k * t[2]];
    const b = side(bends[j]);
    opposite[j] = ap[0] * b[0] + ap[1] * b[1] + ap[2] * b[2] < -0.2 * (Math.hypot(ap[0], ap[1], ap[2]) || 1);
  }
  const closest = solved.massClosest.length ? Math.min(...solved.massClosest) : Infinity;
  let almost = Infinity;
  for (const s of goals) {
    const st = unlensed.seeds[s.id];
    if (st) almost = Math.min(almost, st.closest / s.radius);
  }
  const ub = unlensed.beams[0];
  const uLen = ub.length[ub.length.length - 1];
  const firstAlong = bends.length && uLen > 0 ? Math.min(1, bends[0].at.s / uLen) : 0;
  const k = sol.length;
  const sizes = bends.map((b) => b.size);
  const mixed = new Set(sizes).size > 1;
  const sBends = opposite.filter(Boolean).length;
  const features: DailyFeatures = { masses: k, seeds: goals.length, sizes, reflections, sBends, closest, almost, firstAlong };

  // Hint 1: the easier deduction.
  let h1: string;
  if (k === 1 && goals.length === 1) {
    h1 = almost <= 8 ? 'The beam already passes close to the seed. One mass beside it can pull it across.' : 'Light bends toward a mass. Put one beside the beam, on the side where the seed lies.';
  } else if (k === 1) {
    h1 = 'After a bend the light runs straight again. Make that new line pass through every seed.';
  } else if (k === 2 && sBends > 0) {
    h1 =
      fnv1a(`${level.id}:h1`) % 2 === 0
        ? 'No single bend reaches every seed: the beam must turn one way, then back the other.'
        : 'A mass only pulls the beam toward itself. These seeds need a turn one way, then a turn back.';
  } else if (k === 2) {
    h1 = 'The beam must turn twice: one mass for each turn, each beside the beam it bends.';
  } else {
    h1 = `The beam must turn ${COUNT_WORDS[k] ?? `${k} times`}, one mass per turn. Bend it onto the seeds in the order it reaches them.`;
  }
  const sharper = mixed ? sharperWords(bends.map((b) => ({ size: b.size, q: solved.massClosest[b.i] }))) : '';
  if (sharper) h1 += ` ${sharper}`;
  const pearls = level.nebula === 'apollonian';
  if (reflections > 0) h1 += ` ${pearls ? 'Pearl walls' : "The web's walls"} are mirrors: follow the light past its bounce.`;

  // Hint 2: the region (the HUD draws a dashed sphere around solution[hintMass] = the first bend).
  const h2 = `The marked sphere holds ${k === 1 ? 'the' : 'the first'} mass, ${alongWords(firstAlong)}.`;

  // Hint 3: the designer's note, the full solution in words.
  const target = (j: number): string => {
    const lo = bends[j].at.s;
    const hi = j + 1 < bends.length ? bends[j + 1].at.s : Infinity;
    const lit = seedS.filter((s) => s > lo && s <= hi).length;
    const before = seedS.filter((s) => s <= lo).length;
    if (lit === 0) return j + 1 < bends.length ? `toward the ${ordinal(j + 1)} mass` : 'into place';
    if (j === bends.length - 1) {
      if (lit === goals.length) return lit === 1 ? 'onto the seed' : 'through every seed';
      return lit === 1 ? 'onto the last seed' : lit === 2 ? 'through the last two seeds' : 'through the last seeds';
    }
    return lit === 1 ? `onto the ${ordinal(before)} seed` : lit === 2 ? `through the ${ordinal(before)} and ${ordinal(before + 1)} seeds` : 'through the next seeds';
  };
  // Compact wording (for three-mass notes that would overflow): the first mass "in the marked sphere"
  // (hint 2 already said where it is) instead of the along-the-beam words, "beam" for "new beam".
  const bendPart = (j: number, compact: boolean): string => {
    const b = bends[j];
    if (j === 0) {
      const where = compact ? 'in the marked sphere' : alongWords(firstAlong);
      return `A ${b.size} mass ${offsetWords(solved.massClosest[b.i], 'beam')}, ${where}, turns it ${target(0)}.`;
    }
    const before = seedS.filter((s) => s <= b.at.s).length;
    const where = before > 0 ? `just past the ${ordinal(before - 1)} seed` : 'before the first seed';
    return `Then a ${b.size} mass ${offsetWords(solved.massClosest[b.i], compact ? 'beam' : 'new beam')}, ${where}, turns it ${bounced[j] ? '' : opposite[j] ? 'back ' : 'again '}${target(j)}.`;
  };
  const remarks: string[] = [];
  if (reflections > 0) {
    const walls = pearls ? (reflections === 1 ? 'a pearl wall' : 'pearl walls') : reflections === 1 ? 'a wall of the web' : 'walls of the web';
    remarks.push(`It bounces off ${walls} on the way.`);
  }
  if (closest <= CLOSE_PASS) remarks.push('Keep the beam out of every shadow: light that crosses one is swallowed.');
  const note = (compact: boolean, nBends: number, nRemarks: number): string =>
    [...bends.slice(0, nBends).map((_, j) => bendPart(j, compact)), ...remarks.slice(0, nRemarks)].join(' ');
  // Never longer than the sanitiser allows, and every bend kept as long as possible: with all remarks,
  // then fewer, each in full and then compact wording; only then are the later bends dropped.
  const maxLen = LEVEL_LIMITS.maxHintLength;
  let h3 = '';
  for (let r = remarks.length; r >= 0 && !(h3.length > 0 && h3.length <= maxLen); r--) {
    h3 = note(false, bends.length, r);
    if (h3.length > maxLen) h3 = note(true, bends.length, r);
  }
  for (let n = bends.length - 1; h3.length > maxLen && n >= 1; n--) h3 = note(true, n, 0);
  if (h3.length > maxLen) h3 = h3.slice(0, maxLen - 1) + '…';

  // The one true thing the level shows (≤ 90 chars), most specific first; the variant by the level id.
  const lines =
    reflections > 0
      ? k === 1
        ? pearls ? TEACH.corner : TEACH.cornerWeb
        : pearls ? TEACH.bounce : TEACH.bounceWeb
      : closest <= CLOSE_PASS
        ? TEACH.close
        : mixed
          ? TEACH.mixed
          : k === 1 && goals.length > 1
            ? TEACH.line
            : k === 1
              ? TEACH.bend
              : k === 2 && sBends > 0
                ? TEACH.s
                : k === 2
                  ? TEACH.series
                  : TEACH.compose;
  const teach = lines[fnv1a(level.id) % lines.length];
  return { hints: [h1, h2, h3], teach, hintMass: bends.length ? bends[0].i : 0, features };
}

// ---------------------------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------------------------

/** Generates the day's level with diagnostics (not memoised; tools use it). */
export function generateDailyReport(dateId: string): DailyReport {
  const t0 = performance.now();
  const plan = dailyPlan(dateId);
  const rep: DailyReport = { dateId, plan, level: null, recipe: null, arena: -1, step: 0, attempts: 0, evals: 0, ms: 0, gates: null, features: null };
  if (!plan) return rep;
  // Tries: the recipe in its arenas, the easier recipes in theirs, then one plain mass anywhere.
  const tries: { recipe: DailyRecipe; arena: number }[] = [];
  for (const r of [plan.recipe, ...plan.fallback]) {
    for (let k = 0; k < Math.min(r.arenas, plan.arenas.length); k++) tries.push({ recipe: r, arena: plan.arenas[k] });
  }
  for (const a of plan.arenas) tries.push({ recipe: PLAIN, arena: a });
  for (let a = 0; a < DAILY_ARENAS.length; a++) if (!plan.arenas.includes(a)) tries.push({ recipe: PLAIN, arena: a });

  const id = `daily-${dateId}`;
  for (let step = 0; step < tries.length; step++) {
    const { recipe, arena } = tries[step];
    const da = DAILY_ARENAS[arena];
    const g = generateLevel({
      nebula: da.nebula,
      clock: da.clock,
      arena: da.arena,
      masses: recipe.masses,
      seed: step === 0 ? plan.seed : hash2(plan.seed, step),
      seedCount: recipe.seedCount,
      seedRadius: recipe.seedRadius,
      almost: recipe.almost,
      maxAttempts: recipe.maxAttempts,
      // Every daily is click-reachable from its vantage (Reach.quickReach, the game's placement code).
      reach: true,
      id,
      chapter: 'daily',
      index: Math.max(1, plan.number),
      name: `Daily #${plan.number}`,
    });
    rep.attempts += g.attempts;
    rep.evals += g.evals;
    if (!g.level) continue;
    // Texts never feed the gates (only geometry and the id do): the verdict stands.
    const d = describe(g.level);
    rep.level = sanitizeLevel({ ...g.level, hints: d.hints, teach: d.teach, hintMass: d.hintMass }) ?? g.level;
    rep.recipe = recipe;
    rep.arena = arena;
    rep.step = step;
    rep.gates = g.report;
    rep.features = d.features;
    break;
  }
  rep.ms = performance.now() - t0;
  return rep;
}

const generated = new Map<string, LevelDef | null>();

/** A deep copy (levels are plain JSON data). */
const copyLevel = (l: LevelDef): LevelDef => JSON.parse(JSON.stringify(l)) as LevelDef;

/**
 * The day's level, generated deterministically at runtime (the bundles are built from exactly this).
 * Memoised per date; returns a fresh copy. null for an invalid id or a day before #1.
 */
export function generateDaily(dateId: string): LevelDef | null {
  let level = generated.get(dateId);
  if (level === undefined) {
    level = generateDailyReport(dateId).level;
    if (dayOf(dateId) >= 0) generated.set(dateId, level);
  }
  return level ? copyLevel(level) : null;
}

// ---------------------------------------------------------------------------------------------
// Bundles
// ---------------------------------------------------------------------------------------------

/** Abandon a bundle request after this long (then generate). */
const FETCH_TIMEOUT_MS = 8000;
/** A month is ~50 KB; anything far larger is not ours. */
const MAX_BUNDLE_CHARS = 4_000_000;

const isRec = (v: unknown): v is Record<string, unknown> => typeof v === 'object' && v !== null && !Array.isArray(v);

/** The month file `{ [dateId]: LevelDef }`, or null on any failure (never throws). */
async function fetchBundle(url: string): Promise<Record<string, unknown> | null> {
  if (typeof fetch !== 'function') return null;
  // Without a document a relative URL resolves against nothing (Node tools): generate instead.
  if (typeof document === 'undefined' && !/^[a-z][a-z0-9+.-]*:/i.test(url)) return null;
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    const ctl = typeof AbortController === 'function' ? new AbortController() : null;
    if (ctl) timer = setTimeout(() => ctl.abort(), FETCH_TIMEOUT_MS);
    const res = await fetch(url, ctl ? { signal: ctl.signal } : undefined);
    if (!res.ok) return null;
    const text = await res.text();
    // The Vite dev server answers a missing file with index.html (200): JSON.parse rejects it.
    if (text.length > MAX_BUNDLE_CHARS) return null;
    const data: unknown = JSON.parse(text);
    return isRec(data) ? data : null;
  } catch {
    return null;
  } finally {
    if (timer !== undefined) clearTimeout(timer);
  }
}

/** Month bundles by URL: in-flight and loaded ones are shared; failures are forgotten (retried next time). */
const bundles = new Map<string, Promise<Record<string, unknown> | null>>();

function monthBundle(url: string): Promise<Record<string, unknown> | null> {
  let p = bundles.get(url);
  if (!p) {
    p = fetchBundle(url).then((b) => {
      if (!b) bundles.delete(url);
      return b;
    });
    bundles.set(url, p);
  }
  return p;
}

/** Runtime generation for loadDaily's fallback: generateDaily, or the same code off the main thread. */
export type DailyGenerate = (dateId: string) => LevelDef | null | Promise<LevelDef | null>;

/**
 * The day's level: the pre-generated monthly bundle `${baseUrl}daily/firstlight/YYYY-MM.json` (relative
 * to the page by default) when it holds a valid entry for the day, else runtime generation by `generate`
 * (identical in Node / Chromium; the browser passes dailyClient.generateDailyAsync so the main thread
 * never blocks). null only for an invalid id or a day before #1.
 */
export async function loadDaily(dateId: string, baseUrl = '', generate: DailyGenerate = generateDaily): Promise<LevelDef | null> {
  if (dayOf(dateId) < 0) return null;
  const base = typeof baseUrl === 'string' ? baseUrl : '';
  const bundle = await monthBundle(`${base}daily/firstlight/${dateId.slice(0, 7)}.json`);
  if (bundle && Object.prototype.hasOwnProperty.call(bundle, dateId)) {
    const level = sanitizeLevel(bundle[dateId]);
    // The labels and the share string come from dailyInfo: a stale entry on another nebula is not used.
    if (level && level.id === `daily-${dateId}` && level.chapter === 'daily' && level.nebula === dailyInfo(dateId).nebula) return level;
  }
  // A level that crossed a worker boundary is re-sanitised (a no-op for generateDaily's canonical output).
  const level = await generate(dateId);
  return level ? sanitizeLevel(level) : null;
}
